services:
  postgres-product:
    image: postgres:18.2
    container_name: postgres-product
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - microshop-network

  postgres-order:
    image: postgres:18.2
    container_name: postgres-order
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    networks:
      - microshop-network

networks:
  microshop-network:
    driver: bridge